logging:
  level: "debug"  # Уровень логирования (можно выбрать "debug", "info", "warn", "error")

engines:
  storage:
    url: "postgres://user:password@localhost:5432/authdb" # URL подключения к базе данных PostgreSQL
    max_open_conns: 10        # Максимальное количество открытых соединений
    max_idle_conns: 5         # Максимальное количество простаивающих соединений
    conn_max_lifetime: "1h"   # Максимальное время жизни соединения

auth:
  jwt:
    access_secret: ""     # Секретный ключ для создания Access-токенов
    refresh_secret: ""    # Секретный ключ для создания Refresh-токенов
    access_expiry_hours: 1                      # Время жизни Access-токена в часах
    refresh_expiry_hours: 168                   # Время жизни Refresh-токена в часах (24*7)

handlers:
  http:
    read_timeout: "10s"     # Таймаут чтения HTTP-запросов
    write_timeout: "10s"    # Таймаут записи HTTP-ответов
    address: "localhost"    # Адрес для прослушивания входящих запросов
    port: "8080"            # Порт для прослушивания входящих запросов

vault:
  address: "http://127.0.0.1:8200"   # Адрес Vault сервера
  token: "example-vault-token"       # Токен доступа к Vault
  path: "secret/data/auth"           # Путь к секретам в Vault
  timeout: "5m"                      # Таймаут подключения к Vault
