// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdateUserRequest update user request
//
// swagger:model UpdateUserRequest
type UpdateUserRequest struct {

	// age
	// Minimum: 16
	Age int64 `json:"age,omitempty"`

	// bio
	Bio string `json:"bio,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// nickname
	Nickname string `json:"nickname,omitempty"`

	// phone number
	PhoneNumber string `json:"phoneNumber,omitempty"`
}

// Validate validates this update user request
func (m *UpdateUserRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAge(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateUserRequest) validateAge(formats strfmt.Registry) error {
	if swag.IsZero(m.Age) { // not required
		return nil
	}

	if err := validate.MinimumInt("age", "body", m.Age, 16, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this update user request based on context it is used
func (m *UpdateUserRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *UpdateUserRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateUserRequest) UnmarshalBinary(b []byte) error {
	var res UpdateUserRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
