// Code generated by go-swagger; DO NOT EDIT.

package authentication

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/HexArch/go-chat/internal/services/auth/internal/handlers/http/api/models"
)

// RefreshTokenOKCode is the HTTP code returned for type RefreshTokenOK
const RefreshTokenOKCode int = 200

/*
RefreshTokenOK Tokens successfully refreshed

swagger:response refreshTokenOK
*/
type RefreshTokenOK struct {

	/*
	  In: Body
	*/
	Payload *models.AuthenticatedUserResponse `json:"body,omitempty"`
}

// NewRefreshTokenOK creates RefreshTokenOK with default headers values
func NewRefreshTokenOK() *RefreshTokenOK {

	return &RefreshTokenOK{}
}

// WithPayload adds the payload to the refresh token o k response
func (o *RefreshTokenOK) WithPayload(payload *models.AuthenticatedUserResponse) *RefreshTokenOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the refresh token o k response
func (o *RefreshTokenOK) SetPayload(payload *models.AuthenticatedUserResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RefreshTokenOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RefreshTokenBadRequestCode is the HTTP code returned for type RefreshTokenBadRequest
const RefreshTokenBadRequestCode int = 400

/*
RefreshTokenBadRequest Bad request

swagger:response refreshTokenBadRequest
*/
type RefreshTokenBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRefreshTokenBadRequest creates RefreshTokenBadRequest with default headers values
func NewRefreshTokenBadRequest() *RefreshTokenBadRequest {

	return &RefreshTokenBadRequest{}
}

// WithPayload adds the payload to the refresh token bad request response
func (o *RefreshTokenBadRequest) WithPayload(payload *models.Error) *RefreshTokenBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the refresh token bad request response
func (o *RefreshTokenBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RefreshTokenBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RefreshTokenUnauthorizedCode is the HTTP code returned for type RefreshTokenUnauthorized
const RefreshTokenUnauthorizedCode int = 401

/*
RefreshTokenUnauthorized Unauthorized

swagger:response refreshTokenUnauthorized
*/
type RefreshTokenUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewRefreshTokenUnauthorized creates RefreshTokenUnauthorized with default headers values
func NewRefreshTokenUnauthorized() *RefreshTokenUnauthorized {

	return &RefreshTokenUnauthorized{}
}

// WithPayload adds the payload to the refresh token unauthorized response
func (o *RefreshTokenUnauthorized) WithPayload(payload *models.Error) *RefreshTokenUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the refresh token unauthorized response
func (o *RefreshTokenUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RefreshTokenUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
